### ISSUE TITLE
[Help wanted] Login Error on the cloud server

### ISSUE THREAD

**Issue by Sweetlemon68** [thu-info-community/thu-info-lib#62]
I'm using this package on the Tencent cloud server, but it always raises `LoginError`, whose `message` attribute is an empty string. However, when I check the info platform, I can see the successful login log there.

When the code is run on local (whether on Tsinghua network or other network), this error seldom occurs. But on the cloud server, it always occurs.

Are there any IP blocks? Or can I just login to the info platform (without loginning to myhome platform) to avoid LoginError? Thanks for your help.

The error log is attached below.

```
UnhandledPromiseRejectionWarning: Error

    at login (/var/user/node_modules/thu-info-lib/dist/lib/core.js:70:19)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

LoginError

    at login (/var/user/node_modules/thu-info-lib/dist/lib/core.js:70:19)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by UNIDY2002** [comment]
Thanks. May I first confirm about the version of the lib you are using?

**Comment by Sweetlemon68** [comment]
> Thanks. May I first confirm about the version of the lib you are using?

Initially `2.0.0-alpha.10`. I switched to the stable version `1.3.5` just now, and the message turns to ` Failed to login to Academic (step 1).`

**Comment by UNIDY2002** [comment]
Okay, I'll try to figure it out these days.

**Comment by UNIDY2002** [comment]
@Sweetlemon68 Hi! Would you mind offering your sample code so that I can reproduce on my own cloud server and see what is happening, thanks!

**Comment by Sweetlemon68** [comment]
> @Sweetlemon68 Hi! Would you mind offering your sample code so that I can reproduce on my own cloud server and see what is happening, thanks!

OK. Here is a minimal working example.

```javascript
'use strict';
var Helper_lib = require("thu-info-lib");

async function flogin(helper,uname,pword){
    await helper.login({userId: uname, password: pword, dormPassword: pword});
}

async function query_seats(helper,conf){
    var libs=await helper.getLibraryList();
    return libs;
}

exports.main = async (event, context) => {
    var return_val = await (async() => {
        var paras = event["queryStringParameters"];
        var unm = paras["uname"];
        var pwd = paras["pword"];
        const helper = new Helper_lib.InfoHelper();
        await flogin(helper,unm,pwd).catch(console.error);
        return query_seats(helper,paras["conf"]);
    })().catch(console.error);
    return return_val;
};
```

**Comment by UNIDY2002** [comment]
I'm sorry that I might not be able to solve the problem by myself. The following code is a minimal example of the login process, and if you are interested, you can try running this code on your server and have a look at where is wrong. (Just installing `thu-info-lib@2.0.0-alpha.10` might be enough.)

```javascript
const {uFetch} = require("thu-info-lib/dist/utils/network");
const {DO_LOGIN_URL, CONFIRM_LOGIN_URL, ID_BASE_URL, ID_LOGIN_URL} = require("thu-info-lib/dist/constants/strings");
const {InfoHelper} = require("thu-info-lib")
const cheerio = require('cheerio');

const login = async (userId, password) => {
    // login to webvpn
    const loginResponse = await uFetch(DO_LOGIN_URL, {
        auth_type: "local",
        username: userId,
        sms_code: "",
        password: password,
    }).then(JSON.parse);
    if (!loginResponse.success) {
        switch (loginResponse.error) {
            case "NEED_CONFIRM":
                await uFetch(CONFIRM_LOGIN_URL, {});
                break;
            default:
                throw new Error(loginResponse.message);
        }
    }

    // login to info2021
    await uFetch(ID_BASE_URL + "10000ea055dd8d81d09d5a1ba55d39ad");
    const response = await uFetch(ID_LOGIN_URL, {
        i_user: userId,
        i_pass: password,
        i_captcha: "",
    });
    if (!response.includes("登录成功。正在重定向到")) {
        console.error(response);
        throw new Error();
    }
    const redirectUrl = cheerio.load(response)("a").attr().href;
    const result = await uFetch(redirectUrl);
    if (!result.includes("我的工作台")) {
        console.error(result);
        throw new Error();
    }
    console.log("Login successfully.");

    // Try to get library list
    console.log(await new InfoHelper().getLibraryList());
};

(async () => {
    await login("xxx", "xxx");
})().catch(console.error);
```

**Comment by Sweetlemon68** [comment]
> I'm sorry that I might not be able to solve the problem by myself. The following code is a minimal example of the login process, and if you are interested, you can try running this code on your server and have a look at where is wrong. (Just installing `thu-info-lib@2.0.0-alpha.10` might be enough.)

I tried it on the cloud server and on the localhost. On the localhost it can work well, but on the server the response while trying to login to INFO doesn't include "登录成功。正在重定向到". The response is pasted in [https://paste.ubuntu.com/p/BY67Zzvz4G/](https://paste.ubuntu.com/p/BY67Zzvz4G/). The page looks like this.

![image](https://user-images.githubusercontent.com/16172713/148187816-689a7a13-f644-4311-8f30-a14688599bab.png)

**Comment by Sweetlemon68** [comment]
> > I'm sorry that I might not be able to solve the problem by myself. The following code is a minimal example of the login process, and if you are interested, you can try running this code on your server and have a look at where is wrong. (Just installing `thu-info-lib@2.0.0-alpha.10` might be enough.)
> 
> I tried it on the cloud server and on the localhost. On the localhost it can work well, but on the server the response while trying to login to INFO doesn't include "登录成功。正在重定向到". The response is pasted in https://paste.ubuntu.com/p/BY67Zzvz4G/. The page looks like this.
> 
> ![image](https://user-images.githubusercontent.com/16172713/148187816-689a7a13-f644-4311-8f30-a14688599bab.png)

I just tested this on a real cloud server and it login successfully, but all tests on serverless functions (both Alibaba cloud and Tencent cloud) fail. So maybe the failure has something to do with the feature of serverless cloud function. I'll do further tests.

**Comment by UNIDY2002** [comment]
> > > I'm sorry that I might not be able to solve the problem by myself. The following code is a minimal example of the login process, and if you are interested, you can try running this code on your server and have a look at where is wrong. (Just installing `thu-info-lib@2.0.0-alpha.10` might be enough.)
> > 
> > 
> > I tried it on the cloud server and on the localhost. On the localhost it can work well, but on the server the response while trying to login to INFO doesn't include "登录成功。正在重定向到". The response is pasted in https://paste.ubuntu.com/p/BY67Zzvz4G/. The page looks like this.
> > ![image](https://user-images.githubusercontent.com/16172713/148187816-689a7a13-f644-4311-8f30-a14688599bab.png)
> 
> I just tested this on a real cloud server and it login successfully, but all tests on serverless functions (both Alibaba cloud and Tencent cloud) fail. So maybe the failure has something to do with the feature of serverless cloud function. I'll do further tests.

It seems like `fetch` operations cannot maintain states (i.e. cookie) of previous operations on serverless functions (just a guess), so maybe the `fetch` operations should be customized according to the features of cloud functions.

Great thanks for your discovery!

**Comment by Sweetlemon68** [comment]
> > > > I'm sorry that I might not be able to solve the problem by myself. The following code is a minimal example of the login process, and if you are interested, you can try running this code on your server and have a look at where is wrong. (Just installing `thu-info-lib@2.0.0-alpha.10` might be enough.)
> > > 
> > > 
> > > I tried it on the cloud server and on the localhost. On the localhost it can work well, but on the server the response while trying to login to INFO doesn't include "登录成功。正在重定向到". The response is pasted in https://paste.ubuntu.com/p/BY67Zzvz4G/. The page looks like this.
> > > ![image](https://user-images.githubusercontent.com/16172713/148187816-689a7a13-f644-4311-8f30-a14688599bab.png)
> > 
> > 
> > I just tested this on a real cloud server and it login successfully, but all tests on serverless functions (both Alibaba cloud and Tencent cloud) fail. So maybe the failure has something to do with the feature of serverless cloud function. I'll do further tests.
> 
> It seems like `fetch` operations cannot maintain states (i.e. cookie) of previous operations on serverless functions (just a guess), so maybe the `fetch` operations should be customized according to the features of cloud functions.
> 
> Great thanks for your discovery!

I tries to print `cookies` in `thu-info-lib/dist/utils/network` and find some differences. It seems that, on cloud functions, when trying to login to info2021, the two fetch response are both the raw WebVPN login page.

The cookies of localhost and cloud functions are shown below.

```text
// Cloud Function
{}                                            // Before all actions
{wengine_vpn_ticket: '**1**'}                 // After login to WebVPN
{wengine_vpn_ticket: '**1**', show_vpn: '0'}  // After uFetch ID_BASE_URL+...
{wengine_vpn_ticket: '**1**', show_vpn: '0'}  // After uFetch ID_LOGIN_URL

// Localhost
{}                                            // Before all actions
{wengine_vpn_ticket: '**2**'}                 // After login to WebVPN
{wengine_vpn_ticket: '**2**', refresh: '1'}   // After uFetch ID_BASE_URL+...
{wengine_vpn_ticket: '**2**', refresh: '1'}   // After uFetch ID_LOGIN_URL
```

**Comment by UNIDY2002** [comment]
@Sweetlemon68 Okay, I can also reproduce the error on my serverless function. I'll see if I can find the reason.

**Comment by UNIDY2002** [comment]
Well, I think we might have to admit that the library does not work on serverless functions since we are unable to control the IP addresses that send our requests.
I tried to rewrite the `fetch` operation using the built-in `https` module and when I was fetching `ID_BASE_URL + "10000ea055dd8d81d09d5a1ba55d39ad"`, I received a response of
```
<a href="/login?logoutByIpChange=true">Found</a>.
```
It maybe indicates that the IP address that handles our requests might not remain constant.
I then made a test by making consecutive requests to my personal website through serverless functions and the hypothesis turned out to be true.
![Screenshot](https://user-images.githubusercontent.com/41641284/148323378-7d1c590f-d517-40c5-b108-f6011555766b.png)

---
Anyway, I believe that as long as the IP problem can be handled, this issue can also be solved.

**Comment by Sweetlemon68** [comment]
> Well, I think we might have to admit that the library does not work on serverless functions since we are unable to control the IP addresses that send our requests. I tried to rewrite the `fetch` operation using the built-in `https` module and when I was fetching `ID_BASE_URL + "10000ea055dd8d81d09d5a1ba55d39ad"`, I received a response of
> 
> ```
> <a href="/login?logoutByIpChange=true">Found</a>.
> ```
> 
> It maybe indicates that the IP address that handles our requests might not remain constant. I then made a test by making consecutive requests to my personal website through serverless functions and the hypothesis turned out to be true. ![Screenshot](https://user-images.githubusercontent.com/41641284/148323378-7d1c590f-d517-40c5-b108-f6011555766b.png)
> 
> Anyway, I believe that as long as the IP problem can be handled, this issue can also be solved.

Oh, IP is the key point. After I chose to use a fixed IP for the function, this problem solved. Thank you for your help!
