### ISSUE TITLE
双清公寓水电费无法查询

### ISSUE THREAD

**Issue by t4rf9** [thu-info-community/thu-info-lib#95]
由于家园网的原因，双清公寓水电费只能在手机版页面（http://m.myhome.tsinghua.edu.cn）查询和充值，电脑版页面不支持。
望予修复！

**Comment by UNIDY2002** [comment]
在家园网接入学校统一认证之前，暂不考虑支持家园网相关功能。
感谢您的理解！

**Comment by t4rf9** [comment]
@UNIDY2002 但是`src/lib/dorm.ts`中电费查询和充值用的就是家园网？

**Comment by UNIDY2002** [comment]
没错，今年五月之前家园网是可以通过统一认证登录的，后来就不行了。因此，现在那些接口也是不可用的。
我对双清的情况并不了解。不过手机端充值必须调用微信接口？如果是这样的话，那也挺难整的。

**Comment by t4rf9** [comment]
明白了，现在需要用家园网专门的账号才可以登录。
我本意是说双清这里在家园网上居然有独立的水电费查询、充值URL，和其他宿舍楼不通用。查询可以不用管微信，充值就必须调用微信了。
